name: Build and deploy to GitHub Pages


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - name: Set Git user information
        env:
          MY_EMAIL: dee-eletrotecnica@gmail.com
          MY_NAME: dee-eletrotecnica
        run: |
          git config --global user.email "dee-eletrotecnica@gmail.com"
          git config --global user.name "dee-eletrotecnica"
          git remote set-url origin https://dee-eletrotecnica:${{ secrets.GH_SECRET }}@github.com/dee-eletrotecnica/dee-eletrotecnica.github.io.git
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
            yarn install --frozen-lockfile
            yarn run build
            npx gh-pages -d dist
